/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ClassRoutine {
  'id' : bigint,
  'routines' : Array<RoutineDay>,
  'author' : Principal,
  'timestamp' : Time,
}
export interface ClassTime {
  'id' : bigint,
  'startTime' : string,
  'weekDay' : string,
  'subject' : string,
  'endTime' : string,
  'teacher' : string,
  'author' : Principal,
}
export interface Homework {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'subject' : string,
  'teacher' : string,
  'dueDate' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export type Role = { 'admin' : null } |
  { 'studentEditor' : null } |
  { 'student' : null };
export interface RoutineDay {
  'periods' : Array<RoutinePeriod>,
  'dayName' : string,
}
export interface RoutinePeriod {
  'startTime' : string,
  'subject' : string,
  'endTime' : string,
  'teacher' : string,
  'periodNumber' : bigint,
}
export interface StudentApplication {
  'username' : string,
  'password' : string,
  'name' : string,
  'section' : string,
  'className' : string,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'username' : string,
  'name' : string,
  'role' : Role,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAnnouncement' : ActorMethod<[string, string], undefined>,
  'addClassRoutine' : ActorMethod<[Array<RoutineDay>], undefined>,
  'addClassTime' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'addHomework' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'approveStudentApplication' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAnnouncement' : ActorMethod<[bigint], undefined>,
  'deleteClassRoutine' : ActorMethod<[bigint], undefined>,
  'deleteClassTime' : ActorMethod<[bigint], undefined>,
  'deleteHomework' : ActorMethod<[bigint], undefined>,
  'demoteToStudent' : ActorMethod<[string], undefined>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllApplications' : ActorMethod<[], Array<StudentApplication>>,
  'getAllClassTimes' : ActorMethod<[], Array<ClassTime>>,
  'getAllHomeworks' : ActorMethod<[], Array<Homework>>,
  'getAllRoutines' : ActorMethod<[], Array<ClassRoutine>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isContentLocked' : ActorMethod<[string, [] | [bigint]], boolean>,
  'isUserApproved' : ActorMethod<[string], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'promoteToEditor' : ActorMethod<[string], undefined>,
  'rejectStudentApplication' : ActorMethod<[string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setItemLock' : ActorMethod<[string, bigint, boolean], undefined>,
  'setMasterLock' : ActorMethod<[boolean], undefined>,
  'setSectionLock' : ActorMethod<[string, boolean], undefined>,
  'submitApplication' : ActorMethod<[StudentApplication], undefined>,
  'updateAnnouncement' : ActorMethod<[bigint, string, string], undefined>,
  'updateClassRoutine' : ActorMethod<[bigint, Array<RoutineDay>], undefined>,
  'updateClassTime' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'updateHomework' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];