/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RoutinePeriod = IDL.Record({
  'startTime' : IDL.Text,
  'subject' : IDL.Text,
  'endTime' : IDL.Text,
  'teacher' : IDL.Text,
  'periodNumber' : IDL.Nat,
});
export const RoutineDay = IDL.Record({
  'periods' : IDL.Vec(RoutinePeriod),
  'dayName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const StudentApplication = IDL.Record({
  'username' : IDL.Text,
  'password' : IDL.Text,
  'name' : IDL.Text,
  'section' : IDL.Text,
  'className' : IDL.Text,
});
export const ClassTime = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Text,
  'weekDay' : IDL.Text,
  'subject' : IDL.Text,
  'endTime' : IDL.Text,
  'teacher' : IDL.Text,
  'author' : IDL.Principal,
});
export const Homework = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'subject' : IDL.Text,
  'teacher' : IDL.Text,
  'dueDate' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const ClassRoutine = IDL.Record({
  'id' : IDL.Nat,
  'routines' : IDL.Vec(RoutineDay),
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'studentEditor' : IDL.Null,
  'student' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'name' : IDL.Text,
  'role' : Role,
});
export const ProfileResponse = IDL.Record({
  'username' : IDL.Text,
  'name' : IDL.Text,
  'role' : Role,
});
export const Student = IDL.Record({
  'principal' : IDL.Principal,
  'profile' : ProfileResponse,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const StudentLoginStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'role' : Role,
  }),
  'rejected' : IDL.Null,
  'invalidCredentials' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addClassRoutine' : IDL.Func([IDL.Vec(RoutineDay)], [], []),
  'addClassTime' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addHomework' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'approveStudentApplication' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'deleteClassRoutine' : IDL.Func([IDL.Nat], [], []),
  'deleteClassTime' : IDL.Func([IDL.Nat], [], []),
  'deleteHomework' : IDL.Func([IDL.Nat], [], []),
  'demoteToStudent' : IDL.Func([IDL.Text], [], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllApplications' : IDL.Func([], [IDL.Vec(StudentApplication)], ['query']),
  'getAllClassTimes' : IDL.Func([], [IDL.Vec(ClassTime)], ['query']),
  'getAllHomeworks' : IDL.Func([], [IDL.Vec(Homework)], ['query']),
  'getAllRoutines' : IDL.Func([], [IDL.Vec(ClassRoutine)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getStudentsList' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isContentLocked' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Bool],
      ['query'],
    ),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'promoteToEditor' : IDL.Func([IDL.Text], [], []),
  'rejectStudentApplication' : IDL.Func([IDL.Text], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setItemLock' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [], []),
  'setMasterLock' : IDL.Func([IDL.Bool], [], []),
  'setSectionLock' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'submitApplication' : IDL.Func([StudentApplication], [], []),
  'tryStudentLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [StudentLoginStatus],
      ['query'],
    ),
  'updateAnnouncement' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateClassRoutine' : IDL.Func([IDL.Nat, IDL.Vec(RoutineDay)], [], []),
  'updateClassTime' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateHomework' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RoutinePeriod = IDL.Record({
    'startTime' : IDL.Text,
    'subject' : IDL.Text,
    'endTime' : IDL.Text,
    'teacher' : IDL.Text,
    'periodNumber' : IDL.Nat,
  });
  const RoutineDay = IDL.Record({
    'periods' : IDL.Vec(RoutinePeriod),
    'dayName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const StudentApplication = IDL.Record({
    'username' : IDL.Text,
    'password' : IDL.Text,
    'name' : IDL.Text,
    'section' : IDL.Text,
    'className' : IDL.Text,
  });
  const ClassTime = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Text,
    'weekDay' : IDL.Text,
    'subject' : IDL.Text,
    'endTime' : IDL.Text,
    'teacher' : IDL.Text,
    'author' : IDL.Principal,
  });
  const Homework = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'subject' : IDL.Text,
    'teacher' : IDL.Text,
    'dueDate' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const ClassRoutine = IDL.Record({
    'id' : IDL.Nat,
    'routines' : IDL.Vec(RoutineDay),
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'studentEditor' : IDL.Null,
    'student' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'name' : IDL.Text,
    'role' : Role,
  });
  const ProfileResponse = IDL.Record({
    'username' : IDL.Text,
    'name' : IDL.Text,
    'role' : Role,
  });
  const Student = IDL.Record({
    'principal' : IDL.Principal,
    'profile' : ProfileResponse,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const StudentLoginStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Record({
      'principal' : IDL.Principal,
      'name' : IDL.Text,
      'role' : Role,
    }),
    'rejected' : IDL.Null,
    'invalidCredentials' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addClassRoutine' : IDL.Func([IDL.Vec(RoutineDay)], [], []),
    'addClassTime' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addHomework' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'approveStudentApplication' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'deleteClassRoutine' : IDL.Func([IDL.Nat], [], []),
    'deleteClassTime' : IDL.Func([IDL.Nat], [], []),
    'deleteHomework' : IDL.Func([IDL.Nat], [], []),
    'demoteToStudent' : IDL.Func([IDL.Text], [], []),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllApplications' : IDL.Func(
        [],
        [IDL.Vec(StudentApplication)],
        ['query'],
      ),
    'getAllClassTimes' : IDL.Func([], [IDL.Vec(ClassTime)], ['query']),
    'getAllHomeworks' : IDL.Func([], [IDL.Vec(Homework)], ['query']),
    'getAllRoutines' : IDL.Func([], [IDL.Vec(ClassRoutine)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getStudentsList' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isContentLocked' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Bool],
        ['query'],
      ),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'promoteToEditor' : IDL.Func([IDL.Text], [], []),
    'rejectStudentApplication' : IDL.Func([IDL.Text], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setItemLock' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool], [], []),
    'setMasterLock' : IDL.Func([IDL.Bool], [], []),
    'setSectionLock' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'submitApplication' : IDL.Func([StudentApplication], [], []),
    'tryStudentLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [StudentLoginStatus],
        ['query'],
      ),
    'updateAnnouncement' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateClassRoutine' : IDL.Func([IDL.Nat, IDL.Vec(RoutineDay)], [], []),
    'updateClassTime' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateHomework' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };